<a href="https://colab.research.google.com/github/Jimmaira01/LinearAlgebra_2ndSem/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for CHE: Matrices

# Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

Matrices can be used to compactly write and work with multiple linear equations, that is, a system of linear equations.  It is a rectangular array of numbers arranged into columns and rows (much like a spreadsheet). Matrix algebra is used in statistics to express collections of data. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

:$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$


### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>

Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


Analyze Matrices

In [21]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')


In [22]:
## Declaring a 2x2 matrix
A = np.array([
    [1,2],
    [3,1]
])
describe_mat (A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [23]:
G = np.array ([
               [1,1,3],
               [2,2,4]
])
describe_mat (G)

Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [27]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [24]:
H = np.array ([1,2,3,4,5])
describe_mat (A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

### According to shape

#### Row and Column Matrices

The horizontal and vertical lines of entries in a matrix are called rows and columns, respectively. The size of a matrix is defined by the number of rows and columns that it contains.  They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [26]:
## Declaring a Row Matrix

row_mat_1D = np.array ([
                        1,2,3
]) 
row_mat_2D = np.array([
                       [1,2,3,-4]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 2 3]

Shape:	(3,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [28]:
col_mat = np.array([
                    [29],
                    [30],
                    [31]
])
describe_mat (col_mat)
            

Matrix:
[[29]
 [30]
 [31]]

Shape:	(3, 1)
Rank:	2



##Square Matrices

A square matrix is an n × n matrix; that is, a matrix having the same number of rows as columns. We could say a matrix is square if  i=j . We can tweak our matrix descriptor function to determine square matrices.

In [29]:
def describe_mat(matrix):
  is_square= True if matrix.shape[0]==matrix.shape[1] else False
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n') 

In [30]:
square_mat = np.array([
                       [29,30,31],
                       [39,40,41],
                       [49,50,51]
])
non_square_mat=np.array([
                          [11,12,13],
                          [21,22,23]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[29 30 31]
 [39 40 41]
 [49 50 51]]

Shape:	(3, 3)
Rank:	2
Is Square:True

Matrix:
[[11 12 13]
 [21 22 23]]

Shape:	(2, 3)
Rank:	2
Is Square:False



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [31]:
def describe_mat(matrix):
  if matrix.size>0:
    is_square=True if matrix.shape[0]==matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\]nIs square:{is_square}\n')
  else :
      print ('Matrix is Null')

In [32]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [33]:
zero_mat_row= np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [34]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [35]:
np.array([
          [2,0,0],
          [0,3,0],
          [0,0,5]
])
# a [1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [36]:
d= np.diag([2,3,5,7])
d.shape[0]==d.shape[1]
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [37]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [38]:
np.identity(11)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

In [39]:
np.array([
          [2,3,4,5],
          [0,4,2,-2],
          [1,0,0,2],
          [0,0,3,1]
])

array([[ 2,  3,  4,  5],
       [ 0,  4,  2, -2],
       [ 1,  0,  0,  2],
       [ 0,  0,  3,  1]])

#### Lower Triangular Matrix

In [40]:
np.array([
          [0,2,3],
          [1,4,2],
          [2,0,0]
])
          

array([[0, 2, 3],
       [1, 4, 2],
       [2, 0, 0]])

#Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.


:$$\theta = 5x + 3y - z$$


2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.


$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$


3. Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

4. Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.


In [ ]:
H = np.tril(G)
H


array([[1, 0, 0],
       [2, 2, 0]])

#Addition

In [41]:
A= np.array([
          [0,2],
          [1,4],
          [2,0]
])
B= np.array([
          [2,3],
          [4,2],
          [0,0]
])   
A+B   

array([[2, 5],
       [5, 6],
       [2, 0]])

In [42]:
2+A ##Broadcasting
# 2*np.ones(a.shape)+A

array([[2, 4],
       [3, 6],
       [4, 2]])

##Subtraction

In [43]:
A-B

array([[-2, -1],
       [-3,  2],
       [ 2,  0]])

In [44]:
3-B

array([[ 1,  0],
       [-1,  1],
       [ 3,  3]])

## Element-wise Multiplication

In [45]:
A*B
np.multiply (A,B)

array([[0, 6],
       [4, 8],
       [0, 0]])

In [46]:
2*A

array([[0, 4],
       [2, 8],
       [4, 0]])